package:
  name: reachtools
  version: 0.0.0alpha20230704

source:
  # git_rev: 
  git_url: https://github.com/HDBI/Paired-Tag

build:
  include_recipe: True

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - cmake

#  run:
#    - 

# test:
#   imports:
#     -

about:
  home: https://github.com/cxzhu/Paired-Tag
#   license: Apache-2.0
#   summary: ''
#   description: |
#     ...
#     ...
#   dev_url: 
#   doc_url: 
#   doc_source_url: 

